//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeepClone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diary
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string Diary_name { get; set; }
    }
}
